name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    name: R ${{ matrix.config.r }} / Bioconductor ${{ matrix.config.bioc }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {r: release, bioc: release}
          - {r: devel, bioc: devel}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      R_BIOC_VERSION: ${{ matrix.config.bioc }}
    steps:
      - uses: actions/checkout@v6
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual")'
